image: cr.genos.nebtex.com/publicdev/golang:1.8

# This is NOT a job and will be ignored by GitLab-CI
.shared_hidden_key: &shared  # This is an anchor
  before_script:
    - mkdir -p /go/src /go/bin /go/src/github.com/nebtex
    - export GOPATH=/go
    - export PATH=$PATH:/go/bin
    - ln -s /builds/publicdev/menshend  /go/src/github.com/nebtex/menshend
    - cd /go/src/github.com/nebtex/menshend
    - echo $PWD
    - add-apt-repository ppa:masterminds/glide --yes &&  apt-get update -y
    - apt-get install glide make curl zip unzip -y

services:
  - vault:latest

variables:
  VAULT_DEV_ROOT_TOKEN_ID: "myroot"
  VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
  SKIP_SETCAP: "yes"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
  - vendor/
  untracked: true

stages:
  - deps
  - test
  - build
  - deploy
  - publish
deps:
  <<: *shared
  stage: deps
  script:
    - glide install
#test:
#  stage: test
#  script:
#    - make test

build_master:
  <<: *shared
  stage: build
  only:
    - master
  script:
    - export MENSHEND_RELEASE=latest
    - bash scripts/bundle_react.sh
    - make build

build_tags:
  <<: *shared
  stage: build
  only:
    - tags
  script:
    - export prefix=v
    - export MENSHEND_RELEASE=${CI_COMMIT_TAG#$prefix}
    - bash scripts/bundle_react.sh
    - make build

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -y && apt-get install curl -y
    - curl --request POST --form token=$MENSHEND_TRIGGER_TOKEN --form ref=master https://git.genos.nebtex.com/api/v4/projects/181/trigger/pipeline


publish docs:
  image: node:6
  only:
    - master
  stage: publish
  script:
    - npm install gitbook-cli -g
    - mkdir -p $HOME/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.name "nebot"
    - git config --global user.email devbot@nebtex.com
    - git config --global user.signingkey $nebot_secret_key_gpg
    - git config --global commit.gpgsign true
    - echo -e "$nebot_key" > $HOME/.ssh/id_rsa
    - echo -e "$nebot_gpg" > $HOME/private.key
    - gpg --import $HOME/private.key
    - chmod 400 $HOME/.ssh/id_rsa
    - cp -rf README.md docs/README.md
    - make docs
