sudo: required
dist: trusty

language: go

services:
  - docker

go:
  - 1.8

addons:
  hosts:
    - vault.localhost

script:
  - echo -e "$nebot_key" > $HOME/.ssh/id_rsa
  - git push git@gitlab.com:nebtex/menshend.git
  - wget https://releases.hashicorp.com/vault/0.7.0/vault_0.7.0_linux_amd64.zip
  - unzip vault_0.7.0_linux_amd64.zip
  - sudo mv vault /bin/vault
  - sudo chmod +x /bin/vault
  - make create_test_services
  - sudo add-apt-repository ppa:masterminds/glide --yes && sudo apt-get update -y
  - sudo apt-get install glide -y
  - glide install
  - bash scripts/bundle_react.sh
  - bash scripts/configure_vault.sh
  - make test
